# Generated by Django 4.0.5 on 2022-06-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConsultorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
            ],
        ),
    ]
